on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            zip \
            unzip \
            autoconf \
            libtool \
            pkg-config \
            libncurses5-dev \
            libstdc++6 \
            libglu1-mesa-dev \
            openjdk-17-jdk

    - name: Install Buildozer
      run: pip install --user --upgrade buildozer

    - name: Initialize Buildozer config
      run: |
        buildozer init || true
        sed -i '/android.accept_sdk_license/d' buildozer.spec
        echo "android.accept_sdk_license = True" >> buildozer.spec
        
        # On force une version stable (API 33) qui évite les erreurs de build-tools
        sed -i 's/#\?android.api =.*/android.api = 33/' buildozer.spec
        sed -i 's/#\?android.minapi =.*/android.minapi = 21/' buildozer.spec
        sed -i 's/#\?android.sdk =.*/android.sdk = 33/' buildozer.spec
        
        sed -i 's/#\?requirements =.*/requirements = python3,kivy,pygame/' buildozer.spec
        sed -i 's/#\?package.name =.*/package.name = jascoserpent/' buildozer.spec
        sed -i 's/#\?package.domain =.*/package.domain = org.jasco/' buildozer.spec
        sed -i 's/#\?title =.*/title = JASCO SERPENT/' buildozer.spec
    - name: Build APK with Buildozer
      run: buildozer -v android debug
        
    - name: Build APK with Buildozer
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
